const CONSTANTS = {
	ADD_MARKET: 'ADD_MARKET',
	EDIT_MARKET: 'EDIT_MARKET',
	DELETE_MARKET: 'DELETE_MARKET',
	UPDATE_MARKET_LIST: 'UPDATE_MARKET_LIST',
	UPDATE_CATEGORY_LIST: 'UPDATE_CATEGORY_LIST',
	ADD_CATEGORY: 'ADD_CATEGORY',
	DELETE_CATEGORY: 'DELETE_CATEGORY',
	UPDATE_HAS_NEXT: 'UPDATE_HAS_NEXT',
	UPDATE_CURSOR: 'UPDATE_CURSOR',
	SET_AUTH_USER: 'SET_AUTH_USER',
	SET_LOADING: 'SET_LOADING',
};

export default CONSTANTS;
