// export { default as Dashboard } from './dashboard/Dashboard';
// export { default as AdminLogin } from './admin-login/AdminLogin';
// export { default as EmployeeView } from './employees/Employees';
// export { default as CustomerView } from './customers/Customers';
// export { default as UserProfileView } from './user-profile/UserProfile';
// export { default as ProductView } from './products/Products';
// export { default as ProductDetailView } from './products/ProductDetail';
// export { default as CategoryView } from './categories/Categories';
// export { default as SettingView } from './settings/Settings';
// export { default as CustomerProfileView } from './customers/profile/CustomerProfile';
// export { default as RebuildView } from './rebuild/Rebuild';

export { default as AdminLogin } from './admin/admin-login/AdminLogin';
export { default as AdminMarketItem } from './admin/market-item/MarketItem';
export { default as AdminMarketList } from './admin/market-list/MarketList';
export { default as UsersMarketItem } from './users/market-item/MarketItem';
export { default as UsersMarketList } from './users/market-list/MarketList';
export { default as AddMarket } from './admin/add-market/AddMarket';
export { default as CategoryList } from './admin/categories/CategoryList';
export { default as SearchResults } from './users/search-results/SearchResults';
